language: ruby
rvm:
  - 2.5.3

branches:
  only:
    - develop

before_install:
  - npm install
  - npm install -g gulp-cli

script: gulp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: TODO
  local_dir: _site
  target_branch: master
  on:
    branch: develop