language: ruby

env:
  - JEKYLL_ENV=production

branches:
  only:
    - develop

before_install:
  - gem update --system
  - gem install bundler
  - npm install
  - npm install -g gulp-cli

script: gulp

deploy:
  edge: true
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: develop
