# Site settings
title: "The Rattle"
subtitle: "A Cautionary Tail"
author: "Neill Leonard Robson"

url: "https://neillrobson.com"
permalink: /blog/:year/:month/:day/:title/
google-analytics: UA-97090131-1
repository: RNanoware/website
plugins:
  - jekyll-feed

email: neillrobson811@gmail.com
twitter_username: RNanoware
github_username: RNanoware
linkedin_username: neillrobson
facebook_username: neill.robson

prose:
  siteurl: "https://neillrobson.com"
  media: "assets"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
      - name: "category"
        field:
          element: "multiselect"
          label: "Category"
          alterable: true
          options: "https://neillrobson.com/categories.jsonp"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false
